name: Deploy to Amazon EB

on:
  workflow_run:
    workflows: ["Java CI with Maven"]
    types:
      - completed
      

env:
  EB_PACKAGE_S3_BUCKET : "zzz-cicd-demo-app"
  EB_APPLICATION_NAME  : "cicd-demo"
  EB_ENVIRONMENT_NAME  : "cicd-demo-env"
  DEPLOY_PACKAGE_NAME  : "cicd-demo-${{ github.sha }}.jar" 
  AWS_REGION           : "us-east-1"



jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Copy JAR file to S3 bucket
      run: aws s3 cp /home/runner/work/cicd_demo/cicd_demo/staging/cicd_demo-0.0.1-SNAPSHOT.jar  s3://${{ env.EB_PACKAGE_S3_BUCKET }}/${{ env.DEPLOY_PACKAGE_NAME }}



